---
- name: Install postifx - Ubuntu
  apt:
      name: postfix
      force: yes
      state: present
  when: ansible_os_family == "Debian"

- name: Install postifx - Archlinux
  pacman:
    name: postfix
    state: present
  when: ansible_os_family == "Archlinux"

- name: Configure postfix main
  template:
      src: postfix_main
      dest: /etc/postfix/main.cf
      mode: 0644
      owner: root
      group: root
  notify:
    - Reload postfix
    - Reload postmap

- name: Configure postfix aliases
  template:
      src: "{{ postfix_aliases_file|default(omit) }}"
      dest: /etc/aliases
      mode: 0644
      owner: root
      group: root
  notify: New aliases
  when: postfix_aliases_file is defined

- name: Configure postfix mailname
  copy:
      content: "{{ postfix_hostname }}"
      dest: /etc/mailname
      mode: 0644
      owner: root
      group: root
  notify: Reload postfix

- name: Set transport map
  template:
      src: transport_map
      dest: "{{ postfix_postmap }}"
      mode: 0644
      owner: root
      group: root
  notify:
    - Reload postfix
    - Reload postmap

- name: Set master config
  copy:
      src: postfix_master
      dest: /etc/postfix/master.cf
      mode: 0644
      owner: root
      group: root
  notify:
    - Reload postfix
    - Reload postmap

- name: Set db configs
  template:
    src: "postfix_db_config"
    dest: "/etc/postfix/virtual_alias_maps.cf"
    mode: 0644
    owner: root
    group: root
  with_items: "{ postifx_db_configs }"

- name: Install postfix admin - Archlinux
  pacman:
    name: postfixadmin
    state: latest
  when: ansible_os_family == "Archlinux"

- name: Configure Postfix Admin
- name: Allow SMTP
  ufw:
    port: 25
    proto: tcp
    rule: allow
