---

- name: Remove sendmail
  apt:
      name: "{{ sendmail_packages }}"
      force: yes
      state: absent
  when: ansible_os_family == "Debian"
  notify: Stop sendmail

- name: Install postfix - Ubuntu
  apt:
      name: postfix
      force: yes
      state: present
  when: ansible_os_family == "Debian"

- name: Install postfix - Archlinux
  pacman:
    name: postfix
    state: present
  when: ansible_os_family == "Archlinux"

- name: Configure postfix main
  template:
      src: postfix_main
      dest: /etc/postfix/main.cf
      mode: 0644
      owner: root
      group: root
  notify:
    - Reload postfix
    - Reload postmap

- name: Create postfix etc - Arch linux
  file:
    path: /var/spool/postfix/etc
    state: directory
    owner: postfix
    group: root
  when: ansible_os_family == "Archlinux"

- name: Copy services - Arch
  copy:
    src: /etc/services
    dest: /var/spool/postfix/etc/services
    remote_src: yes
    owner: postfix
    group: root
    mode: 0644
  notify: Reload postfix
  when: ansible_os_family == "Archlinux"

- name: Copy resolv - Arch
  copy:
    src: /etc/resolv.conf
    dest: /var/spool/postfix/etc/resolv.conf
    remote_src: yes
    owner: postfix
    group: root
    mode: 0644
  notify: Reload postfix
  when: ansible_os_family == "Archlinux"

- name: Copy nsswitch - Arch
  copy:
    src: /etc/nsswitch.conf
    dest: /var/spool/postfix/etc/nsswitch.conf
    remote_src: yes
    owner: postfix
    group: root
    mode: 0644
  notify: Reload postfix
  when: ansible_os_family == "Archlinux"

- name: Configure postfix mailname
  copy:
      content: "{{ postfix_hostname }}"
      dest: /etc/mailname
      mode: 0644
      owner: root
      group: root
  notify: Reload postfix

- name: Set transport map
  template:
      src: transport_map
      dest: "{{ postfix_postmap }}"
      mode: 0644
      owner: root
      group: root
  notify:
    - Reload postfix
    - Reload postmap

- name: Set master config
  copy:
      src: postfix_master
      dest: /etc/postfix/master.cf
      mode: 0644
      owner: root
      group: root
  notify:
    - Reload postfix
    - Reload postmap

- name: Allow SMTP
  ufw:
    port: 25
    proto: tcp
    rule: allow
