---

- name: Remove postifx - Ubuntu
  apt:
      name: postfix
      force: yes
      state: absent
  when: ansible_os_family == "Debian"
  notify: Stop postifx

- name: Install sendmail
  apt:
      name: "{{ sendmail_packages }}"
      force: yes
      state: present
  when: ansible_os_family == "Debian"
  notify: Restart sendmail
